- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
> RQLY-767 HTTP method filter support

- src/main/actions/events/constants.js
- src/main/actions/events/index.ts
- src/main/main.ts
The UI handler for this is part of https://github.com/requestly/requestly/pull/700
> feat: events from main to UI + quit event

- src/main/actions/networkSessionStorage/index.js
- src/main/events.js
Supporting PR for https://github.com/requestly/requestly/pull/959
> feat: symlink network sessions to original file if possible

- README.md
Issue: https://github.com/requestly/requestly-desktop-app/issues/57
> fix(README): contributing link + small typo

- package-lock.json
- release/app/package-lock.json
- release/app/package.json
- src/renderer/actions/apps/browsers/close-warning-tab.js
> chore: comment out mockttp code

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
introduces android emulator support - https://github.com/requestly/requestly-desktop-app/pull/95
> chore: version bump to v1.7.0

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- fix cert generation issue - https://github.com/requestly/requestly-desktop-app/pull/97
> chore: version bump to v1.7.1

- package-lock.json
- package.json
- release/app/package-lock.json
- removes file-upload fix due to regression
> chore: bump version to v1.7.3

- release/app/package-lock.json
- release/app/package.json
missed here - https://github.com/requestly/requestly-desktop-app/pull/103
> chore-fix: add updated version to release/app/package.json

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
forgot to update the actual package version 😓 [here](https://github.com/requestly/requestly-desktop-app/pull/113)
> chore: version bump to v1.7.6

- release/app/package-lock.json
- src/renderer/actions/helperSocketServer.ts
- src/renderer/actions/proxy/startProxyServer.ts
Corresponding PR: https://github.com/requestly/requestly/pull/2282
> [ENGG-2394] fix: added fallback for extension websocket port

- src/main/main.ts
- src/main/menu.ts
Supports App zoom-in and zoom-out using `CMD+ +` and `CMD+ -`
https://github.com/requestly/requestly-desktop-app/pull/123
> feat: support zoom in out

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- src/renderer/actions/apps/browsers/chromium-based-browsers.js
currently only works for chromium based browsers
fixes -  https://github.com/requestly/requestly-desktop-app/issues/121
related UI made compatible - https://github.com/requestly/requestly/pull/2613
> feat: blocklist

- src/renderer/actions/local-files/index.ts
- src/renderer/actions/local-files/sample/base.ts
- src/renderer/actions/local-files/sample/service.ts
- src/renderer/index.js
- src/renderer/lib/RPCServiceOverIPC.ts
corresponding UI  - https://github.com/requestly/requestly/pull/2684
> chore: code from group discussion

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
releasing backend for local synced workspace #133 + some bug fixes
> chore: bump version to v2.0.0

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
updated changes from yet-to-be released https://github.com/requestly/requestly-desktop-app/pull/147 with fixes for deploy pipeline
- update electron notarize to fix deploy pipeline
- bump version to v2025.04.13
> v2025.04.13

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
Releases:
- ensure static command path is not used  https://github.com/requestly/requestly-desktop-app/pull/151
- fixes to fetching local workspaces https://github.com/requestly/requestly-desktop-app/pull/150
> chore: bump version to v25.5.1

- package-lock.json
- package.json
- release/app/package-lock.json
https://github.com/requestly/requestly-proxy/pull/61
> fix: updated to patched version of requestly-proxy

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- releasing support for storing specific networks logs to local file - https://github.com/requestly/requestly-desktop-app/pull/164
> chore: bump version to v25.5.25

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- releasing https://github.com/requestly/requestly-desktop-app/pull/172
> chore: bump version to v25.6.5

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- src/main/actions/cookiesHelpers.ts
- src/main/actions/getProxiedAxios.ts
- src/main/actions/makeApiClientRequest.js
- src/main/main.ts
port for https://github.com/requestly/requestly/pull/3125
> feat: basic cookie support for api client

- src/main/actions/cookiesHelpers.ts
alternative to https://github.com/requestly/requestly-desktop-app/pull/178
> fix: suppress set cookie errors

- .eslintrc.js
- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- https://github.com/requestly/requestly-desktop-app/pull/179
> chore: bump version to v25.6.19

- package.json
- release/app/package-lock.json
got missed in https://github.com/requestly/requestly-desktop-app/pull/181
> fix: remove explicit certname for windows

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- https://github.com/requestly/requestly-desktop-app/pull/185
> chore: bump version to v25.6.27

- package.json
- src/lib/autoupdate/index.js
- src/main/actions/cleanup.js
- src/main/actions/logNetworkRequest.js
- src/main/actions/logNetworkRequestV2.js
- src/main/actions/startBackgroundProcess.js
- src/main/events.js
- src/main/main.ts
- src/main/menu.ts
- src/renderer/actions/helperSocketServer.ts
- src/renderer/actions/initEventHandlers.js
- src/renderer/actions/proxy/startProxyServer.ts
- src/renderer/actions/shutdown.js
- src/renderer/actions/startHelperServer.js
- src/renderer/lib/proxy-interface/loggerService.js
Reverts requestly/requestly-desktop-app#191
was causing issues on windows
> Revert "refactor: delegate quit to main renderer"

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- https://github.com/requestly/requestly-desktop-app/pull/202
> chore: bump version to v25.8.29
