requestly/requestly-desktop-app

- package.json
- release/app/package.json
- src/renderer/actions/apps/os/proxy/windows.js
Before windows 11, in order for system proxy settings to apply, we used a hacky approach to launch and kill a new internet explorer window. 
This is no longer required in windows 11, but with microsoft dropping support for Internet explorer from windows 11 onwards, this launches the following error dialog if we use `exec`
> RQLY-345 Handling error on iexplorer.exe launch after windows 11 dropped support for internet explorer

- src/renderer/actions/apps/os/proxy/osx.js
The proxy list is read and not overwritten based on it's value when Requestly is started.
So any changes made while Requestly is running might be overwritten.
> RQLY-440 fix: added meet.google.com to proxy bypass list on OSX

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
removes preserve cookie
pinning @types/keyv to v3.1.4 for now
refer [this issue](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62793) for more context
> chore: version bump v1.4.11

- src/lib/storage/constants/index.ts
- src/renderer/actions/apps/index.js
- src/renderer/actions/apps/os/proxy/index.js
- src/renderer/actions/initEventHandlers.js
- src/renderer/actions/startProxyServer.ts
- src/renderer/actions/storage/cacheUtils.ts
- src/renderer/config/index.js
- src/renderer/types/index.ts
Could had directly used the cache of `UserPreference` store. But to also cover the case when `getNextAvailablePort` might adjust the port number if the cached port number is currently in use:
Added `proxyServerStatus` to the `global.rq` namespace in Background process.
> RQLY-634 chore: remove port IPC calls for launching apps

- src/main/actions/getProxiedAxios.ts
fixes https://github.com/requestly/requestly/issues/652
currently shows a blocking error dialog for fresh installs.
This happens because of a race condition between saving the certificate locally and the api client reading it for creating the axios client.
> fix: add try catch to handle error during race condition

- package.json
- src/main/main.ts
App will registers itself as a client for `requestly://` protocol
Also added support to force redirects when navigated to desktop app using this protocol.
Specify the path you want to redirect to using the `route` search param as such `requestly://desktop-app?route=/path/to/something`
The supporting pr for this (https://github.com/requestly/requestly/pull/692) includes utilities for the same
> feat: set requestly protocol handler

- .erb/scripts/notarize.js
- package.json
Changes around notarization steps for macOS
- start using `notarytool` instead of the long deprecated `alttool` 
- stops redundant internal calls to notarize (electron builder is the one who actually triggers notarization)
- renders `.erb/scripts/notarize.js` useless (still added fixes, in case we decide to switch in the future)
Now the build will only require `APPLE_APP_SPECIFIC_PASSWORD` and `APPLE_ID` to be correctly set in the environment
Verified auto upgrade flow does not break!
> Use notarytool 

- package.json
rollout fix for failing secure websockets - https://github.com/requestly/requestly-proxy/pull/26
> chore: update requestly-proxy to v1.1.23

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
upgrades requestly core to enable new internal debugging feature
shipping this: https://github.com/requestly/requestly/pull/1027
> chore: version bump to v1.5.11

- package.json
- release/app/package.json
updated windows metadata to make it possible to sign app with physical ev.
Note: `rfc3161TimeStampServer` can be occasionally removed while signing to try the default time stamping server when this one fails
> Fix: windows code signing process

- .erb/configs/webpack.config.renderer.dev.ts
- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- could not bump to v29 since it has some issues with the ts transpiler. [This issue](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/3568) gives a good overview and can be referenced later during the next upgrade. Also - https://github.com/TypeStrong/ts-node/issues/1997
- updated `webpack.config.renderer.dev` to avoid a deprecated warning
- a critical vulnerability still exists inside the `releases/app` but that is due to a [not-yet-fixed lodash release](https://github.com/advisories/GHSA-p6mc-m468-83gw) (lodash.patch)
> chore: electron version bump to v27

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- electron version update - #87
- upgrade vulnerable repos - #89 & #83 
- updated version of requestly proxy - https://github.com/requestly/requestly-proxy/pull/44
- other hygiene cleanups and also run `npm audit fix`
> chore: bump version to v1.6.1

- package-lock.json
- package.json
yet to be properly tested inside requestly-desktop-dev, but mergin for now.
> chore: update electron-updater to remove security vulnerability.

- src/main/actions/makeApiClientRequest.js
When API client request throw error status code, it was leading to an exception
> fix: api client not working for errored requests

- .github/workflows/release_desktop_app.yml
- src/main/actions/makeApiClientRequest.js
- src/renderer/actions/apps/os/ca/windows.js
- update node version in the pipeline
- made asset publishing mandatory, this is risky, so need to be extra cautious to have a draft release ready before the pipeline is triggered
> chore: update release pipeline to make it work for linux

- package-lock.json
- package.json
- src/main/actions/startBackgroundProcess.js
- src/main/main.ts
- src/packages/rq_proxy/ssl-proxying/ssl-proxying-manager.ts
- src/renderer/actions/apps/mobile/adb-commands.ts
- src/renderer/actions/initEventHandlers.js
- src/renderer/index.js
- src/utils/sentryInit.js
- sentry init removed from renderer
- adb scripts had some Buffer to UInt8Array casting that was not working, needs to be tested
- added `eslint-disable` to `main.ts` to avoid annoying linter bugs
- updated vulnerable packages, and removed unused ones.
- updated requestly-core version - https://github.com/requestly/requestly/pull/2222
> chore: cleanup and minor fixes + update requestly-core version

- src/main/events.js
- src/renderer/actions/startHelperServer.js
We can't know for sure, but for now we are assuming if someone hits the helper server to get the required scripts, then they eventually get their terminal connected to Requestly
only [the last commit](https://github.com/requestly/requestly-desktop-app/pull/118/commits/6c65c7fa123d161c8b50d24409a0c50a0dee584d) is relevant, the rest is just cleanup.
> track terminal helper server connected

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- add fallback websocket port https://github.com/requestly/requestly-desktop-app/pull/115
- support for ios simulators https://github.com/requestly/requestly-desktop-app/pull/116
- upgrade vulnerable dependencies https://github.com/requestly/requestly-desktop-app/pull/117
- track and send event to webapp when helper server is hit https://github.com/requestly/requestly-desktop-app/pull/118
> chore: version bump to v1.7.7

- package-lock.json
- release/app/package-lock.json
did not upgrade the vulnerable axios version right now since that is a breaking change because:
- there aren't clear migration guides - [ref](https://github.com/axios/axios/discussions/4996)
- our use (in here) is restricted to api client request, hence fairly minimal. though this is critical case for requestly-proxy
> chore: ran npm audit fix

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
_Going forward versions would be vYYYY.MM.DD corresponding to date of release_
- feat: local workspaces
> chore: bump version to v2025.04.11

- assets/requirement.rqset
verified [separately](https://github.com/requestly/requestly-desktop-dev/releases) that this does not cause any issues with auto updates
> chore: add new certificate to DR

- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
releasing:
- `serveWithoutRequest` for modify response with local file: 
- Proxy changes: https://github.com/requestly/requestly-proxy/pull/59 
- Corresponding UI: https://github.com/requestly/requestly/pull/3005
- Added new certificate authority to Designated Requirements https://github.com/requestly/requestly-desktop-app/pull/162
- This _(and any releases beyond this)_ would hence be the intermediate releases for the Authority migration process for macOS
> chore: bump version to v25.5.19

- .eslintrc.js
- package-lock.json
- package.json
- release/app/package-lock.json
- release/app/package.json
- updates the eslint config to only warn on unused variables and allow them if starting with an underscore
Releases:
- https://github.com/requestly/requestly-desktop-app/pull/191
> chore: bump version to v25.7.21
